### ISSUE TITLE
ModuleNotFoundError upon `en_typus` import

### ISSUE THREAD

**Issue by danaksim** [byashimov/typus#1]
I noticed an error when trying to import `en_typus`:
```
>>> from typus import en_typus
...
ModuleNotFoundError: No module named 'typus.processors'
```

That probably happens because passing `packages=['typus']` to `setuptools.setup` does not make setuptools recursively search for child packages inside the `typus` package and therefore include anything besides the `typus` itself. That results in `typus.processors` not being included in the installation:
```
→ ls venv/lib/python3.7/site-packages/typus
__init__.py __pycache__ chars.py    core.py     utils.py
```

The solution would be to either include the `processors` package explicitly by setting `packages=['typus', 'typus.processors']` or to use the `setuptools.find_packages` function and include everything but `tests`: `packages=find_packages(exclude=('tests',))`.

**Comment by byashimov** [comment]
Thanks for report. Please check the latest dev.

**Comment by danaksim** [comment]
That seems to do the trick. Thanks.
