### ISSUE TITLE
Hyphens, dashes and spaces: some improvements and a bug

### ISSUE THREAD

**Issue by danaksim** [byashimov/typus#2]
Here are some things that could probably be improved.

1. According to [1, appx. 15; 2], in Russian em dash requires narrow spaces around it, not normal ones. That would probably work for English as well. Although traditional rules of English [3] require no spaces around em dashes, [4] states that it is a matter of style and that “AP Stylebook”, for example, recommends putting full-width spaces around em dashes.

   So I suggest using narrow non-breaking spaces before em dashes and thin spaces after in both English and Russian.

2. Number ranges should be typeset with en dashes instead of em dashes.

   Em dashed number ranges are usually seen in Russian [1, sec. 6.1.5] since Russian typography has no tradition of using en dashes whatsoever, but there’s hardly any point in following that. En dashes look better with numbers [5].

3. Phone numbers should be typeset with hyphens and/or spaces, not en dashes [1, sec. 6.1.6; 6]. That’s really just formatting needed for readability, dashes make no sense here.

4. Now this one is just a bug, I guess.

   I noticed that `expr_ranges` does not replace hyphens with dashes if the range is followed by a math operator, which makes sense. The regular expression, however, forbids only math operators preceded by a non-zero number of spaces.

   Therefore, `1-2 = 4` becomes `1&minus;2&nbsp;= 4`, but `1-2=4` becomes `1&mdash;2=4`.

   And all the test cases have spaces before math operators, which, it seems, is why it was left unnoticed.

I could probably fix all that and send a PR. What do you think?

### References

1. Мильчин, Чельцова. Справочник издателя и автора. 3-е издание.

2. https://ru.wikipedia.org/wiki/Неразрывный_пробел#Правила_применения_в_наборе

3. https://en.oxforddictionaries.com/grammar/dash-and-em-dash

4. https://apvschicago.com/2011/05/em-dashes-and-ellipses-closed-or-spaced.html

5. https://www.artlebedev.ru/kovodstvo/sections/158/

6. https://www.artlebedev.ru/kovodstvo/sections/91/

**Comment by byashimov** [comment]
Hi! I'll look at this closer on the weekends and fix this on my own. It's great to see people take care about this little things. I'll be glad if you could provide test case right here on the issue page: (source, expected) pairs.
Thanks for your report.

**Comment by danaksim** [comment]
Okay. I'll use symbol names as they are defined in `typus.chars` plus “THINSP” for thin space.

### test_mdash

So, most of the `test_mdash` cases should remain the same assuming that `MDASH_PAIR` becomes `NNBSP + MDASH + THINSP`.

Except for one thing. As I have just surprisingly learned, em dash requires no preceding space if there is a comma:

![__ _ _ _ _ _ _djvu_-_djview](https://user-images.githubusercontent.com/11201186/49670892-2beffb00-fa77-11e8-90f0-f75caff0978c.jpg)
That means that
```python
(', - foo', f',{MDASH_PAIR}foo')
(', -- foo', f',{MDASH_PAIR}foo')
```
should be changed to
```python
(', - foo', f',{MDASH_PAIR[1:]}foo')
(', -- foo', f',{MDASH_PAIR[1:]}foo')
```

### test_ranges

Here `MDASH` should be replaced with `NDASH` in all test cases.

Also account for math operators without preceding spaces:
```python
# Skips
# ... all the current skips
('2-3=4', '2-3=4'),
('2-3*4', '2-3*4'),
```

### test_phones

With this one I'm not really sure what to suggest. Maybe the phone replaces should be disabled/removed altogether. It would be possible to apply some formatting to international 11-digit numbers, but with 7-digit ones, which are currently detected, there's nothing to do.

**Comment by byashimov** [comment]
Okey, let's go step by step starting from the easiest.

1. Phones. There is no visual difference between hyphen and hyphen-minus. Even Artemy uses hyphen-minus on his phones page. So it seems like I can drop it out with no regret and 7-11 digits headache. What do you think about it?
2. Ranges. OK and done (not pushed yet)
3. Mdash pair -- in progress.

**Comment by danaksim** [comment]
Yes, keeping hyphen-minuses in phone numbers is exactly what I had in mind. I don't think they should be replaced with real hyphens (`&#8208;`).

**Comment by byashimov** [comment]
Check [this](https://github.com/byashimov/typus/pull/3) branch out :)

**Comment by danaksim** [comment]
Looked it through. It seems that the no-space-before-math bug I was talking about is still there. Otherwise everything's great.

So, about the bug. I don't really understand what you did in e9b70a598bb7b75cbc30119abeb120a41b508639.

In `test_expressions` you basically added
```python
# Doesn't affect math
(f'1{MDASH}2=4', f'1{MDASH}2=4')
```
and assured that it is skipped by `expr_ranges`. But it is skipped because there is an em dash, not because there's a math operator after. Maybe em dashes are there by accident and you meant to use hyphens?

And in `test_summary` you made sure that `'3-3=0'` becomes `'3&minus;3=0'`, but the reason this thing gets skipped by `expr_ranges` is not the math operator but the second number not being greater than the first.

As I see it, in the `expr_ranges` method the third regex line of `expr` should be changed from `r'(?!{0}+{1}|{2})'` to `r'(?!{0}*{1}|{2})'`, and that's it. Then you can test that `expr_range` skips stuff like `'1-2=4'`, which it will.

**Comment by byashimov** [comment]
Bad copy issue. Thanks for your help. Have updated PR, please take a look once more.

**Comment by danaksim** [comment]
Yup, now it's fixed. Thanks. Guess that finishes this issue off, so feel free to close it anytime.

**Comment by byashimov** [comment]
Thanks for your help. I'll try release this features asap!
